export const strings = {
  common: {
    pending: "Pendiente",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    back: "Volver",
    save: "Guardar",
    noNotes: "Sin notas",
  },
  tabs: {
    home: "Inicio",
    calculate: "Calcular",
    subjects: "Ramos",
    simulate: "Simular",
    settings: "Config.",
  },
  modal: {
    title: "Este es un modal",
    goHome: "Ir al inicio",
  },
  quickCalculator: {
    initialEvaluationName: (index: number) => `Prueba n°${index}`,
    quickSubjectName: "Cálculo rápido",
    defaultEvaluationName: "Evaluación",
    statusNotAvailable: "—",
    reviewWeights: "Revisar ponderaciones",
    pending: "Pendiente",
    noAdvice: "Sin consejo disponible.",
    completeWeightsAdvice:
      "Completa las ponderaciones hasta llegar a 100% para obtener un cálculo confiable.",
    heroTitle: "Calcula tu escenario académico en segundos",
    heroDescription:
      "Agrega tus evaluaciones, deja pendientes las notas que aún no tienes y revisa qué necesitas para aprobar.",
    stepDefineWeights: "1. Define ponderaciones",
    stepEnterGrades: "2. Ingresa tus notas",
    stepReviewResult: "3. Revisa tu resultado",
    reminderPendingGrade:
      "Una nota vacía se toma como pendiente, no como cero.",
    addEvaluation: "Agregar evaluación",
    beforeStartTitle: "Antes de comenzar",
    beforeStartDescription:
      "Ingresa tus evaluaciones, notas y ponderaciones. Las notas pendientes no se calculan como cero.",
    quickSettingsTitle: "Configuración rápida",
    minimumPassingGradeLabel: "Nota mínima de aprobación",
    minimumPassingGradeError: (minGrade: number, maxGrade: number) =>
      `La nota mínima debe estar entre ${minGrade} y ${maxGrade}.`,
    evaluationsTitle: "Evaluaciones",
    temporaryEditSubtitle: "Edición temporal",
    gradeError: (minGrade: number, maxGrade: number) =>
      `La nota debe estar entre ${minGrade} y ${maxGrade}.`,
    weightError: "La ponderación debe estar entre 0 y 100.",
    evaluationNumber: (index: number) => `Evaluación #${index}`,
    nameLabel: "Nombre",
    gradeLabel: "Nota",
    weightLabel: "Ponderación (%)",
    addEvaluationWithPrefix: "+ Agregar evaluación",
    totalWeightWarning: (totalWeight: number) =>
      `La suma de ponderaciones es ${totalWeight.toFixed(0)}%. Para calcular la nota necesaria, debe ser 100%.`,
    totalWeightSuccess: "Perfecto: tu ponderación total está en 100%.",
    summaryTitle: "Resumen académico",
    liveUpdateSubtitle: "Actualización en tiempo real",
    totalWeightTitle: "Suma de ponderaciones",
    projectionAdjustPending:
      "Aún falta ajustar al 100% para una proyección exacta.",
    projectionAdjustDone:
      "Perfecto: ponderación completa para proyectar con confianza.",
    clear: "Limpiar",
    howItsCalculated: "¿Cómo se calcula?",
    howItsCalculatedDescription:
      "La nota se calcula mediante promedio ponderado. Cada evaluación aporta a la nota final según su porcentaje. Las evaluaciones sin nota se consideran pendientes y no se cuentan como cero.",
    evaluationPlaceholder: (index: number) => `Evaluación ${index}`,
  },
  subjectsTab: {
    globalStatusTitle: "Estado global de tus ramos",
    overallProgress: "Progreso general rendido",
    total: "Total",
    withEvaluations: "Con evaluaciones",
    atRisk: "En riesgo",
    startByAdding:
      "Comienza agregando tu primer ramo para activar tu panel visual.",
    noSubjectsTitle: "Aún no tienes ramos registrados.",
    noSubjectsDescription:
      "Crea tu primer ramo para guardar evaluaciones, ponderaciones, notas pendientes y calcular tu estado académico durante el semestre.",
    add: "Agregar",
    yourSubjectsTitle: "Tus ramos",
    yourSubjectsSubtitle: "Guardados localmente en este dispositivo",
    minimumGradePrefix: "Nota mínima:",
    noEvaluations: "Sin evaluaciones",
    distributionHelp: "Cada bloque representa un ramo",
    legendPositive: "Aprobado/Favorable",
    legendRisk: "En riesgo",
    legendNegative: "Reprobado/No alcanzable",
    legendPending: "Pendiente",
    perSubjectChecklistTitle: "¿Qué podrás revisar por ramo?",
    checklistCurrentAverage: "Promedio ponderado actual",
    checklistAccumulatedPoints: "Puntos acumulados",
    checklistWeightProgress: "Ponderación rendida y pendiente",
    checklistRequiredGrade: "Nota necesaria para aprobar",
    checklistAcademicStatus: "Estado académico automático",
    checklistMostImportantPending: "Evaluación pendiente más importante",
    nextImprovementTitle: "Siguiente mejora",
    nextImprovementDescription:
      "Pronto podrás crear ramos, agregar evaluaciones y guardar tu avance localmente en el dispositivo.",
  },
  subjectDetail: {
    deleteEvaluationTitle: "Eliminar evaluación",
    deleteEvaluationMessage: (evaluationName: string) =>
      `¿Eliminar "${evaluationName}"? Esta acción no se puede deshacer.`,
    deleteSubjectTitle: "¿Eliminar este ramo?",
    deleteSubjectMessage:
      "También se eliminarán todas sus evaluaciones asociadas.",
    deleteSubjectButton: "Eliminar ramo",
    deleteFailedTitle: "No se pudo eliminar",
    deleteFailedMessage: "Intenta nuevamente en unos segundos.",
    stackTitle: "Detalle del ramo",
    badge: "Detalle del ramo",
    description: "Controla tus evaluaciones y avance académico en este ramo.",
    summaryTitle: "Resumen del ramo",
    minimumGrade: "Nota mínima",
    color: "Color",
    editSubject: "Editar ramo",
    noGrades: "Sin notas",
    pendingCalculation: "Pendiente de cálculo",
    noPending: "Sin pendientes",
    evaluationsTitle: "Evaluaciones",
    registeredCount: (count: number) =>
      `${count} registrada${count > 1 ? "s" : ""}`,
    emptyEvaluations:
      "Aún no tienes evaluaciones. Agrega la primera para calcular tu avance.",
    pendingBadge: "Pendiente",
    gradeBadge: (gradeValue: string) => `Nota ${gradeValue}`,
    weight: "Ponderación",
    addEvaluation: "Agregar evaluación",
    riskZoneTitle: "Zona de riesgo",
    riskZoneDescription:
      "Esta acción eliminará el ramo y todas sus evaluaciones en este dispositivo.",
    deletingSubject: "Eliminando ramo...",
    notFoundTitle: "Ramo no encontrado",
    notFoundDescription: "No se encontró el ramo. Intenta volver atrás.",
  },
  simulator: {
    heroTitle: "Escenario visual",
    initialState: "Estado inicial",
    simulatedProjection: "Proyección simulada",
    noBase: "Sin base",
    projection: "Proyección",
    noSimulation: "Sin simulación",
    hint: "Prueba una nota y mira cómo cambia tu escenario",
    importantTitle: "Importante",
    noDataChanges: "No modifica tus datos",
    noDataChangesDescription: "Esta simulación no modifica tus notas reales.",
    selectSubjectTitle: "1. Selecciona un ramo",
    noSubjects: "No hay ramos disponibles para simular.",
    minimumGradePrefix: "Nota mínima:",
    selectPendingEvaluationTitle: "2. Selecciona evaluación pendiente",
    noEvaluations: "Este ramo aún no tiene evaluaciones registradas.",
    noPendingEvaluations:
      "Este ramo no tiene evaluaciones pendientes para simular.",
    weightPrefix: "Ponderación:",
    simulatedGradeTitle: "3. Nota simulada",
    simulatedGradeLabel: "Ingresa la nota simulada",
    simulatedGradePlaceholder: "Ej: 5.5",
    calculate: "Calcular",
    resultTitle: "4. Resultado proyectado",
    projectedAverage: "Promedio proyectado",
    projectedStatus: "Estado proyectado",
    projectedRequiredGrade: "Nota necesaria proyectada",
    noValidGrades: "Sin notas válidas",
    noPending: "Sin pendientes",
    simulatedGradeRequired: "La nota simulada es obligatoria.",
    simulatedGradeInvalid: "Ingresa una nota válida usando números.",
    gradeRangeError: (minGrade: number, maxGrade: number) =>
      `La nota debe estar entre ${minGrade} y ${maxGrade}.`,
  },
  settings: {
    system: "Sistema",
    light: "Claro",
    dark: "Oscuro",
    systemDescription: "Usa automáticamente el modo de tu dispositivo.",
    lightDescription: "Prioriza legibilidad en ambientes luminosos.",
    darkDescription: "Reduce brillo y fatiga visual en ambientes oscuros.",
    chileanScale: "Escala chilena",
    scaleDescription:
      "Rango activo: 1.0 a 7.0 (extensible en futuras versiones).",
    projectFallbackName: "Calculadora Académica Mobile",
    invalidNumericValue: "Ingresa un valor numérico válido.",
    globalMinRangeError: "La nota mínima global debe estar entre 1.0 y 7.0.",
    deleteAllSubjectsTitle: "Eliminar todos los ramos",
    deleteAllSubjectsMessage:
      "Se eliminarán todos los ramos y evaluaciones guardadas en este dispositivo.",
    deletedDataTitle: "Datos eliminados",
    deletedDataMessage: "Todos los ramos fueron eliminados correctamente.",
    resetAppTitle: "Reiniciar aplicación",
    resetAppMessage:
      "Se eliminarán ramos, evaluaciones y configuraciones personalizadas.",
    resetButton: "Reiniciar",
    appResetTitle: "Aplicación reiniciada",
    appResetMessage: "La configuración volvió a su estado inicial.",
    appThemeTitle: "Tema de la aplicación",
    appThemeDescription:
      "El cambio se guarda automáticamente y se mantiene al volver a abrir la app.",
    academicConfigTitle: "Configuración académica",
    globalMinLabel: "Nota mínima global",
    globalMinPlaceholder: "Ej: 4.0",
    active: "Activo",
    saving: "Guardando...",
    behaviorTitle: "Comportamiento",
    academicAdviceTitle: "Consejos académicos",
    academicAdviceDescription:
      "Muestra recomendaciones automáticas según tu estado actual.",
    riskAlertsTitle: "Alertas de riesgo",
    riskAlertsDescription:
      "Activa notificaciones visuales cuando haya ramos críticos.",
    animationsTitle: "Animaciones",
    animationsDescription:
      "Habilita transiciones y microanimaciones de la interfaz.",
    dataTitle: "Datos",
    dataDescription:
      "Estas acciones son locales y no requieren conexión a internet.",
    deleteSubjects: "Eliminar ramos",
    resetApp: "Reiniciar app",
    infoTitle: "Información",
    project: "Proyecto",
    version: "Versión",
    developedBy: "Desarrollado por",
    developedByValue: "José Noe",
    github: "GitHub",
    githubValue: "@JoseNoeT",
    infoDescription:
      "Panel de configuración local para pruebas académicas y ajustes de experiencia.",
  },
  createSubject: {
    headerTitle: "Agregar ramo",
    headerDescription:
      "Configura una asignatura para controlar tus notas durante el semestre.",
    subjectDataTitle: "Datos del ramo",
    subjectNameLabel: "Nombre del ramo",
    subjectNamePlaceholder: "Ej: Matemáticas I",
    passingGradeLabel: "Nota mínima de aprobación",
    passingGradePlaceholder: "4.0",
    academicSystemTitle: "Sistema académico",
    academicSystemDescription:
      "Este sistema viene desde tu configuración académica y se aplicará solo a este ramo.",
    colorIdentifier: "Color identificador del ramo",
    whyCreateTitle: "¿Por qué crear un ramo?",
    whyCreateDescription:
      "Al crear un ramo podrás agregar evaluaciones, registrar notas pendientes, revisar tu avance y calcular la nota necesaria para aprobar.",
    saveSubject: "Guardar ramo",
    nameRequired: "El nombre del ramo es obligatorio.",
    gradeRangeError: (minGrade: number, maxGrade: number) =>
      `La nota mínima debe estar entre ${minGrade} y ${maxGrade}.`,
    savedMessage: "Ramo guardado localmente en el dispositivo.",
    saveFailedMessage: "No se pudo guardar el ramo localmente.",
  },
  createEvaluation: {
    stackTitle: "Agregar evaluación",
    headerTitle: "Agregar evaluación",
    headerDescription:
      "Registra una evaluación para este ramo. La nota puede quedar pendiente si aún no la tienes.",
    dataTitle: "Datos de la evaluación",
    nameLabel: "Nombre",
    namePlaceholder: "Ej: Prueba 1",
    weightLabel: "Ponderación (%)",
    weightPlaceholder: "Ej: 30",
    gradeLabel: "Nota (dejar vacío si es pendiente)",
    pendingTitle: "¿La nota es pendiente?",
    pendingDescription:
      "Si aún no tienes la nota, deja el campo vacío. Podrás editarla después desde el detalle del ramo.",
    saving: "Guardando...",
    saveEvaluation: "Guardar evaluación",
    nameRequired: "El nombre de la evaluación es obligatorio.",
    weightRangeError: "La ponderación debe estar entre 1 y 100.",
    gradeRangeError: (minGrade: number, maxGrade: number) =>
      `La nota debe estar entre ${minGrade} y ${maxGrade}.`,
  },
  editSubject: {
    stackTitle: "Editar ramo",
    loadingTitle: "Cargando ramo...",
    waitMessage: "Espera un momento.",
    unavailableTitle: "No disponible",
    missingSubject: "El ramo no existe o fue eliminado.",
    loadFailed: "No se pudo cargar el ramo.",
    headerTitle: "Editar ramo",
    headerDescription: "Actualiza el nombre, nota mínima y color del ramo.",
    dataTitle: "Datos del ramo",
    nameLabel: "Nombre del ramo",
    namePlaceholder: "Ej: Matemáticas I",
    minGradeLabel: "Nota mínima de aprobación",
    minGradePlaceholder: "4.0",
    colorIdentifier: "Color identificador del ramo",
    saving: "Guardando...",
    saveChanges: "Guardar cambios",
    nameRequired: "El nombre del ramo es obligatorio.",
    gradeRangeError: (minGrade: number, maxGrade: number) =>
      `La nota mínima debe estar entre ${minGrade} y ${maxGrade}.`,
    saveFailed: "No se pudo guardar los cambios.",
  },
  editEvaluation: {
    stackTitle: "Editar evaluación",
    loadingTitle: "Cargando evaluación...",
    waitMessage: "Espera un momento.",
    unavailableTitle: "No disponible",
    missingEvaluation: "La evaluación no existe o no pertenece a este ramo.",
    loadFailed: "No se pudo cargar la evaluación.",
    headerTitle: "Editar evaluación",
    headerDescription: "Actualiza nombre, nota y ponderación para este ramo.",
    dataTitle: "Datos de la evaluación",
    nameLabel: "Nombre",
    namePlaceholder: "Ej: Prueba 1",
    weightLabel: "Ponderación (%)",
    weightPlaceholder: "Ej: 30",
    gradeLabel: "Nota (vacía = pendiente)",
    saving: "Guardando...",
    saveChanges: "Guardar cambios",
    nameRequired: "El nombre de la evaluación es obligatorio.",
    weightRangeError: "La ponderación debe estar entre 0 y 100.",
    gradeRangeError: (minGrade: number, maxGrade: number) =>
      `La nota debe estar entre ${minGrade} y ${maxGrade}.`,
    saveFailed: "No se pudo guardar los cambios de la evaluación.",
  },
  home: {
    defaultInfoMessage:
      "Comienza creando tu primer ramo para activar el panel.",
    currentSituationTitle: "Tu situación actual",
    currentAverage: "Promedio actual",
    subjectCount: "Cantidad de ramos",
    subjectsAtRisk: "Ramos en riesgo",
    pendingEvaluations: "Evaluaciones pendientes",
    noGrades: "Sin notas",
    alertsTitle: "Alertas académicas",
    critical: "Crítica",
    attention: "Atención",
    positive: "Positivo",
    info: "Información",
    insightsTitle: "Análisis",
    risk: "Riesgo",
    nextActionsTitle: "Próximas acciones",
    trendTitle: "Tendencia",
    noTrendTitle: "Sin tendencia aún",
    noTrendDescription:
      "Crea tu primer ramo para comenzar a calcular tu progreso académico.",
    insufficientDataTitle: "Datos insuficientes",
    insufficientDataDescription:
      "Agrega evaluaciones para calcular una tendencia real.",
    trendUp: "Tendencia al alza",
    trendDown: "Tendencia a la baja",
    trendStable: "Tendencia estable",
    trendDescription: "Basada en el progreso rendido de tus ramos activos.",
    pulseInsufficientData:
      "Aún no hay notas registradas para calcular un pulso real.",
    pulseNoSubjects:
      "Crea tu primer ramo para activar indicadores con datos reales.",
    featuredSubjectsTitle: "Ramos prioritarios",
    featuredSubjectsSubtitle: (visibleCount: number, totalCount: number) => {
      if (totalCount <= 0) {
        return "Sin ramos registrados aún.";
      }

      if (totalCount <= 3) {
        const noun = totalCount === 1 ? "ramo" : "ramos";
        return `Mostrando ${visibleCount} de ${totalCount} ${noun}.`;
      }

      return `Mostrando 3 de ${totalCount} ramos destacados por urgencia académica.`;
    },
    emptyFeaturedSubjects:
      "Aún no hay ramos para destacar. Crea tu primer ramo y comienza a construir tu panel.",
    viewAllSubjects: "Ver todos los ramos",
    averagePrefix: "Promedio:",
    pendingPrefix: "Pendientes:",
  },
  academicSummary: {
    pending: "Pendiente",
    title: "Resumen académico",
    subtitle: "Actualización en tiempo real",
    statusLabel: "Estado académico",
    accumulatedPoints: "Puntos acumulados",
    currentWeightedAverage: "Promedio ponderado actual",
    completedWeight: "Ponderación rendida",
    pendingWeight: "Ponderación pendiente",
    requiredGrade: "Nota necesaria",
    finalProjectedGrade: "Nota final proyectada",
    completedProgress: "Progreso rendido",
    pendingProgress: "Progreso pendiente",
    contextualAdvice: "Consejo contextual",
  },
} as const;
